import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Links = [
  { href: "/", label: "Hoome" },
  { href: "/docs", label: "Docs" },
  { href: "/todo", label: "Todo" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <header>
          <nav>
            <ul className="flex items-center space-x-3">
              {Links.map((link) => (
                <li key={link.href}>
                  <Link className="link link-hover" href={link.href}>
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <h1>Root layout</h1>
        <main>{children}</main>
      </body>
    </html>
  );
}
